export const items = [
	{ id: 1, name: 'Arroz', price: 5.99, category: 'Grãos' },
	{ id: 2, name: 'Feijão', price: 7.49, category: 'Grãos' },
	{ id: 3, name: 'Macarrão', price: 3.29, category: 'Massas' },
	{ id: 4, name: 'Óleo de Soja', price: 4.99, category: 'Óleos' },
	{ id: 5, name: 'Sal', price: 1.59, category: 'Temperos' },
	{ id: 6, name: 'Açúcar', price: 2.99, category: 'Açúcares' },
	{ id: 7, name: 'Café', price: 8.79, category: 'Bebidas Quentes' },
	{ id: 8, name: 'Leite', price: 3.49, category: 'Laticínios' },
	{ id: 9, name: 'Pão', price: 2.19, category: 'Padaria' },
	{ id: 10, name: 'Carne Moída', price: 12.99, category: 'Carnes' },
	{ id: 11, name: 'Frango', price: 9.99, category: 'Carnes' },
	{ id: 12, name: 'Peixe', price: 14.99, category: 'Carnes' },
	{ id: 13, name: 'Ovos', price: 4.29, category: 'Ovos' },
	{ id: 14, name: 'Tomate', price: 2.79, category: 'Vegetais' },
	{ id: 15, name: 'Cebola', price: 1.99, category: 'Vegetais' },
	{ id: 16, name: 'Alho', price: 0.99, category: 'Temperos' },
	{ id: 17, name: 'Batata', price: 2.49, category: 'Vegetais' },
	{ id: 18, name: 'Banana', price: 3.69, category: 'Frutas' },
	{ id: 19, name: 'Maçã', price: 4.99, category: 'Frutas' },
	{ id: 20, name: 'Laranja', price: 3.49, category: 'Frutas' },
];
